### PR TITLE
Fix: Flower splash when start activity, and fix flower disappear afte…

### LINKED ISSUE #20: Flower will splash in LoveLockActivity when leveraging.

### PR DESCRIPTION
**Pull request by HunkD**
…r system recycle memory for WeakReference.

Fix #20 and #17

### CODE REVIEW

File: Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java [hunk 1]
```diff
@@ -86,15 +110,12 @@ public void stopAnimation() {
...
+        public Flower(Bitmap bitmap) {
             // TODO: lazy load
-            BitmapFactory.Options options = new BitmapFactory.Options();
-            options.inSampleSize = 4;
-            mWeakBitmap = new WeakReference<>(
-                    BitmapFactory.decodeResource(getContext().getResources(), mResId, options));
+            mWeakBitmap = bitmap;
 
             mPaint = new Paint();
+            mPaint.setAlpha(0);
```
Comment (HunkD) [inline Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java]: I forgot to reset the alpha to 0 when initialize the object, so flower will have splash and become normal after start activity.

File: Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java [hunk 2]
```diff
@@ -86,15 +110,12 @@ public void stopAnimation() {
         private long mWaitTimeStart = -1;
         private long mShowingTimeDuration;
 
-        public Flower(@DrawableRes int resId) {
-            this.mResId = resId;
+        public Flower(Bitmap bitmap) {
             // TODO: lazy load
-            BitmapFactory.Options options = new BitmapFactory.Options();
-            options.inSampleSize = 4;
-            mWeakBitmap = new WeakReference<>(
```
Comment (HunkD) [inline Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java]: Use directly reference to draw.

File: Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java [hunk 3]
```diff
@@ -31,18 +39,35 @@ public FlowerFrame(Context context, AttributeSet attrs) {
 
     public FlowerFrame(Context context, AttributeSet attrs, int defStyleAttr) {
         super(context, attrs, defStyleAttr);
+    }
+
+    private List<Bitmap> registerBitmap() {
```
Comment (HunkD) [inline Fancy/app/src/main/java/com/hunkd/fancy/extension/view/FlowerFrame.java]: This method will save memory for using duplicate picture in flower object. I created 10 bitmap object for 5 unique images before, so waste half of memory for duplicate images.
